# states.py
class UserState:
    MAIN_MENU = "main_menu"
    CREATING_BOT = "creating_bot"
    BOT_MENU = "bot_menu"
    EDITING_TOKEN = "editing_token"
    EDITING_WELCOME = "editing_welcome"
    ADDING_CLASS = "adding_class"
    EDITING_CLASS = "editing_class"
    ADDING_SUBJECT = "adding_subject"
    EDITING_SUBJECT = "editing_subject"
    ADDING_TOPIC = "adding_topic"
    EDITING_TOPIC_NAME = "editing_topic_name"
    EDITING_TOPIC_CONTENT = "editing_topic_content"
    EDITING_TOPIC_FILE = "editing_topic_file"
    VIEWING_PREDEFINED = "viewing_predefined"
    ADDING_STUDENT = "adding_student"
    ADDING_STUDENT_CLASS = "adding_student_class"
    REMOVING_STUDENT = "removing_student"
    ADDING_MATERIAL = "adding_material"
    ADDING_MATERIAL_CLASS = "adding_material_class"
    ADDING_MATERIAL_TITLE = "adding_material_title"
    ADDING_MATERIAL_DESCRIPTION = "adding_material_description"
    ADDING_MATERIAL_CONTENT = "adding_material_content"
    ADDING_MATERIAL_FILE = "adding_material_file"

class StudentState:
    MAIN_MENU = "main_menu"
    VIEWING_SUBJECTS = "viewing_subjects"
    VIEWING_TOPICS = "viewing_topics"
    READING_TOPIC = "reading_topic"
    VIEWING_ADDITIONAL_MATERIALS = "viewing_additional_materials"
    READING_MATERIAL = "reading_material"